SOURCE_TIER_CORE = "core"
SOURCE_TIER_EXPERIMENTAL = "experimental"
SOURCE_TIER_STRATEGIC = "strategic"

INVENTORY_MODEL_LIVE_FEED = "live_feed"
INVENTORY_MODEL_PUBLIC_INVENTORY = "public_inventory"
INVENTORY_MODEL_EVERGREEN_APPLICATION = "evergreen_application"
INVENTORY_MODEL_PUBLIC_TEASER = "public_teaser"
INVENTORY_MODEL_CORPORATE_CAREERS = "corporate_careers"
INVENTORY_MODEL_STRATEGIC_SIGNAL = "strategic_signal"
INVENTORY_MODEL_MIXED = "mixed"

# Developer note for future mixed sources:
# Source-level classification is only a default. For mixed sources, or any
# count_live source that emits evergreen, teaser, strategic, or otherwise
# non-live records, providers must explicitly set
# include_in_live_market_estimate=False on those JobCandidate rows.

MARKET_COUNT_POLICY_COUNT_LIVE = "count_live"
MARKET_COUNT_POLICY_REPORT_SEPARATELY = "report_separately"
MARKET_COUNT_POLICY_EXCLUDE_LIVE_ESTIMATE = "exclude_live_estimate"

OPPORTUNITY_KIND_LIVE_POSTING = "live_posting"
OPPORTUNITY_KIND_PUBLIC_INVENTORY_OPPORTUNITY = "public_inventory_opportunity"
OPPORTUNITY_KIND_EVERGREEN_APPLICATION = "evergreen_application"
OPPORTUNITY_KIND_PUBLIC_TEASER = "public_teaser"
OPPORTUNITY_KIND_CORPORATE_CAREERS_POSTING = "corporate_careers_posting"
OPPORTUNITY_KIND_STRATEGIC_SIGNAL = "strategic_signal"
OPPORTUNITY_KIND_RAW_VARIANT = "raw_variant"

AVAILABILITY_BASIS_API_FEED = "api_feed"
AVAILABILITY_BASIS_PUBLIC_FEED = "public_feed"
AVAILABILITY_BASIS_PUBLIC_CMS = "public_cms"
AVAILABILITY_BASIS_PUBLIC_PAGE = "public_page"
AVAILABILITY_BASIS_PUBLIC_TEASER_PAGE = "public_teaser_page"
AVAILABILITY_BASIS_EVERGREEN_PAGE = "evergreen_page"
AVAILABILITY_BASIS_CORPORATE_CAREERS_PAGE = "corporate_careers_page"
AVAILABILITY_BASIS_LOGIN_GATED_AFTER_APPLY = "login_gated_after_apply"
AVAILABILITY_BASIS_UNKNOWN = "unknown"

DEFAULT_SOURCE_TIER = SOURCE_TIER_CORE
DEFAULT_INVENTORY_MODEL = INVENTORY_MODEL_LIVE_FEED
DEFAULT_MARKET_COUNT_POLICY = MARKET_COUNT_POLICY_COUNT_LIVE
DEFAULT_OPPORTUNITY_KIND = OPPORTUNITY_KIND_LIVE_POSTING
DEFAULT_AVAILABILITY_BASIS = AVAILABILITY_BASIS_API_FEED
DEFAULT_INCLUDE_IN_LIVE_MARKET_ESTIMATE = 1

EXPERIMENTAL_SOURCE_SLUGS = ("invisible",)

OPPORTUNITY_KIND_BY_INVENTORY_MODEL = {
    INVENTORY_MODEL_LIVE_FEED: OPPORTUNITY_KIND_LIVE_POSTING,
    INVENTORY_MODEL_PUBLIC_INVENTORY: OPPORTUNITY_KIND_PUBLIC_INVENTORY_OPPORTUNITY,
    INVENTORY_MODEL_EVERGREEN_APPLICATION: OPPORTUNITY_KIND_EVERGREEN_APPLICATION,
    INVENTORY_MODEL_PUBLIC_TEASER: OPPORTUNITY_KIND_PUBLIC_TEASER,
    INVENTORY_MODEL_CORPORATE_CAREERS: OPPORTUNITY_KIND_CORPORATE_CAREERS_POSTING,
    INVENTORY_MODEL_STRATEGIC_SIGNAL: OPPORTUNITY_KIND_STRATEGIC_SIGNAL,
    INVENTORY_MODEL_MIXED: OPPORTUNITY_KIND_LIVE_POSTING,
}

AVAILABILITY_BASIS_BY_INVENTORY_MODEL = {
    INVENTORY_MODEL_LIVE_FEED: AVAILABILITY_BASIS_API_FEED,
    INVENTORY_MODEL_PUBLIC_INVENTORY: AVAILABILITY_BASIS_PUBLIC_FEED,
    INVENTORY_MODEL_EVERGREEN_APPLICATION: AVAILABILITY_BASIS_EVERGREEN_PAGE,
    INVENTORY_MODEL_PUBLIC_TEASER: AVAILABILITY_BASIS_PUBLIC_TEASER_PAGE,
    INVENTORY_MODEL_CORPORATE_CAREERS: AVAILABILITY_BASIS_CORPORATE_CAREERS_PAGE,
    INVENTORY_MODEL_STRATEGIC_SIGNAL: AVAILABILITY_BASIS_UNKNOWN,
    INVENTORY_MODEL_MIXED: AVAILABILITY_BASIS_UNKNOWN,
}


def default_opportunity_kind_for_inventory_model(inventory_model):
    return OPPORTUNITY_KIND_BY_INVENTORY_MODEL.get(
        inventory_model,
        DEFAULT_OPPORTUNITY_KIND,
    )


def default_availability_basis_for_inventory_model(inventory_model):
    return AVAILABILITY_BASIS_BY_INVENTORY_MODEL.get(
        inventory_model,
        DEFAULT_AVAILABILITY_BASIS,
    )


def include_in_live_market_estimate_for_policy(market_count_policy):
    return int(market_count_policy == MARKET_COUNT_POLICY_COUNT_LIVE)
