"""Security-bounded, ephemeral foundations for AI-assisted profile intake."""

from wahojobs.profile_intake.adapter import (
    DeterministicFakeProfileExtractionAdapter,
    ProfileExtractionAdapter,
)
from wahojobs.profile_intake.contracts import (
    AI_EXTRACTION_SCHEMA_VERSION,
    DEFAULT_DOCUMENT_LIMITS,
    AIProfileExtraction,
    DocumentFormat,
    DocumentKind,
    DocumentLimits,
    EvidenceBlock,
    EvidencePacket,
    EXPLICIT_ONLY_EXTRACTION_FIELD_PATHS,
    ExtractedDocument,
    ExtractedFact,
    INFERRED_ONLY_EXTRACTION_FIELD_PATHS,
    ModelEvidenceBlock,
    ModelEvidencePacket,
    ParserMetadata,
    ProfileIntakeError,
    SUPPORTED_EXTRACTION_FIELD_PATHS,
    new_document_reference,
    validate_ai_profile_extraction,
)
from wahojobs.profile_intake.documents import (
    extract_profile_document,
    extract_resume_document,
)
from wahojobs.profile_intake.minimization import (
    MODEL_EVIDENCE_SCHEMA_VERSION,
    minimize_evidence_packet,
    require_minimized_model_evidence,
)
from wahojobs.profile_intake.openai_adapter import (
    DEFAULT_PROFILE_EXTRACTION_MODEL,
    PROFILE_EXTRACTION_PROMPT_VERSION,
    OpenAIProfileExtractionAdapter,
    OpenAIProfileExtractionError,
    ProfileExtractionDiagnostics,
    ProfileExtractionOutcome,
    configured_openai_profile_adapter,
    profile_extraction_structured_output_schema,
    profile_extraction_system_prompt,
)
from wahojobs.profile_intake.review_draft import (
    REVIEW_DRAFT_SCHEMA_VERSION,
    AIProfileReviewDraft,
    ReviewDraftFact,
    ReviewDraftIssue,
    ReviewDraftSource,
    ReviewSourceAttribution,
    ValidatedProfileSource,
    build_profile_review_draft,
    reconcile_profile_extractions,
)

__all__ = (
    "AI_EXTRACTION_SCHEMA_VERSION",
    "DEFAULT_DOCUMENT_LIMITS",
    "AIProfileExtraction",
    "AIProfileReviewDraft",
    "DEFAULT_PROFILE_EXTRACTION_MODEL",
    "DeterministicFakeProfileExtractionAdapter",
    "DocumentFormat",
    "DocumentKind",
    "DocumentLimits",
    "EvidenceBlock",
    "EvidencePacket",
    "EXPLICIT_ONLY_EXTRACTION_FIELD_PATHS",
    "ExtractedDocument",
    "ExtractedFact",
    "INFERRED_ONLY_EXTRACTION_FIELD_PATHS",
    "MODEL_EVIDENCE_SCHEMA_VERSION",
    "ModelEvidenceBlock",
    "ModelEvidencePacket",
    "OpenAIProfileExtractionAdapter",
    "OpenAIProfileExtractionError",
    "ParserMetadata",
    "ProfileExtractionAdapter",
    "ProfileExtractionDiagnostics",
    "ProfileExtractionOutcome",
    "ProfileIntakeError",
    "PROFILE_EXTRACTION_PROMPT_VERSION",
    "REVIEW_DRAFT_SCHEMA_VERSION",
    "ReviewDraftFact",
    "ReviewDraftIssue",
    "ReviewDraftSource",
    "ReviewSourceAttribution",
    "SUPPORTED_EXTRACTION_FIELD_PATHS",
    "ValidatedProfileSource",
    "build_profile_review_draft",
    "configured_openai_profile_adapter",
    "extract_profile_document",
    "extract_resume_document",
    "new_document_reference",
    "minimize_evidence_packet",
    "profile_extraction_structured_output_schema",
    "profile_extraction_system_prompt",
    "reconcile_profile_extractions",
    "require_minimized_model_evidence",
    "validate_ai_profile_extraction",
)
